security:
    encoders:
        Example3Bundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        users:
            entity:
                class: Example3Bundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: example_3_login
                check_path: example_3_login_check
                username_parameter: login_type[login]
                password_parameter: login_type[password]
                default_target_path: /example-3
                #Target can be specified as a form parameter ex.
                #target_path_parameter: login_type[redirect]
                provider: users
            logout:
                path: /example-3/logout
                target: /example-3

    access_control:
      - { path: ^/example-3, roles: IS_AUTHENTICATED_ANONYMOUSLY}
