security:
    encoders:
        Example2Bundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        users:
            entity:
                class: Example2Bundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: example_2_login
                check_path: example_2_login_check
                username_parameter: login_type[login]
                password_parameter: login_type[password]
                default_target_path: /example-2
                #Target can be specified as a form parameter ex.
                #target_path_parameter: login_type[redirect]
                provider: users
            logout:
                path: /example-2/logout
                target: /example-2

    access_control:
      - { path: ^/example-2, roles: IS_AUTHENTICATED_ANONYMOUSLY}
