services:
    authentication.two_factor.listener:
        class: Example5Bundle\EventListener\TwoFactorAuthenticationListener
        arguments:
            - @router
            - @doctrine.orm.default_entity_manager
            - @mailer
        public: false

    authentication.two_factor.redirect.listener:
        class: Example5Bundle\EventListener\TwoFactorRedirectListener
        arguments:
            - @security.token_storage
            - @templating
            - @router
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: -1}

    comment.voter:
         class: Example5Bundle\Voter\CommentVoter
         arguments:
             - @service_container
         tags:
             - { name: security.voter }